# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b615ee06ccdc202b94fb1166d93f487670426abaa21fd033094ba35f7f35d55917c487ec7d66d62aaf8e9d2ecf578a319feb3d06f5df1ec6e39437eff1e168f7

test:
  secret_key_base: 07510ec18a854df00d7c3dec5e0ca50b86ea87296f315b24aa317cee3b02af0a965b3b71422b84687a958d6d7b02e28bfe5267b599b69b059cee5fcf50e7acc0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
