# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22d318d53bceab9ead65e5d1667fadc78a2097cc3bea46457487a243e0786207cafea05cdaded9bd8090d2cf2c56b79ca864eb79c0bf75d7ba978739ac783959

test:
  secret_key_base: 610a57b44757d22b7bb7641ee7cefe05744af50b166ba5d4fbda2c9d95e71a14818812034471f531c8692e6b5d20dad9c5049b62560013f4886dccab992a760f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
