# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cc0c2185072494d7b8b92a74c254e1e260eb96c688d8f981b63013f2e6b0c3dd9be3385ec1f8f931931ec8be5f584b300fdc89cb3bb6dbb09f221a6e2ba3ebc

test:
  secret_key_base: dedc8faf5872bbb44fbf122109ac7e72ea534d9ed93de7e540509a4ad0c380302fb72e4bb5221380b0d91f8066b5082a1a853525f23fdf7de13343c31cfbb4ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
